// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/ethanrichardson/Development/my-app/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/ethanrichardson/Development/my-app/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('my-app', appParameters);
});
var entryPoint = require('/Users/ethanrichardson/Development/my-app/index.js');